application: myproject 
environment: aaaa 
namespace: default 
address: 0.0.0.0 
cluster:
  expose: true
  spec:

 
    
    bootstrap:
      initdb:
        dataChecksums: true

    imageName: ghcr.io/cloudnative-pg/postgresql:16.6
    instances: 3



    primaryUpdateMethod: switchover
    primaryUpdateStrategy: supervised

    resources:
      limits:
        cpu: 2 # Doubled in production

    storage:
      size: 2Gi
      storageClass: local-path

    walStorage:
      size: 4Gi # Doubled in utils, production
      storageClass: local-path
