---
# Source: cnpg-cluster/templates/Cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    helm.sh/chart: cnpg-cluster-2.1.6
  name: myproject-db-devel
  namespace: default
spec:
  bootstrap:
    initdb:
      database: myproject_devel
      dataChecksums: true
      owner: myproject_devel
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6
  instances: 3
  managed:
    roles:
    - comment: Read-only user template
      name: myproject_devel_readonly
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: supervised
  storage:
    size: 2Gi
    storageClass: local-path
  walStorage:
    size: 4Gi
    storageClass: local-path
